const LOCALSTACK_IMAGE_VERSION = '4.0.2';
const POSTGRESQL_IMAGE_VERSION = '17';
const MARIADB_IMAGE_VERSION = '11.7.1';
const MYSQL_IMAGE_VERSION = '9.1.0';
const JAVA_IMAGE_VERSION = '17.0.13_11-jre-jammy';

export default {
    JAVA_VERSION: '17',
    MAVEN_VERSION: '3.9.9',
    GRADLE_VERSION: '8.11.1',
    DEFAULT_APP_VERSION: '0.0.1-SNAPSHOT',
    SPRING_BOOT_VERSION: '3.4.0',
    SPRING_CLOUD_VERSION: '2024.0.0',
    SPRING_CLOUD_AWS_VERSION: '3.2.1',
    SPRING_DEP_MNGMNT_VERSION: '1.1.6',
    MYBATIS_PLUS_VERSION: '3.5.9',
    SPRINGDOC_OPENAPI_VERSION: '2.7.0',
    COMMONS_IO_VERSION: '2.16.1',
    LOKI_LOGBACK_APPENDER: '1.3.2',
    PALANTIR_JAVA_FORMAT_VERSION: '2.50.0',

    JACOCO_MIN_COVERAGE_REQUIRED: '0.80',

    GRADLE_GIT_PROPERTIES_PLUGIN_VERSION: '2.4.2',
    GRADLE_JACOCO_PLUGIN_VERSION: '0.8.12',
    GRADLE_SONAR_PLUGIN_VERSION: '5.1.0.4882',
    GRADLE_BENMANES_VERSIONS_PLUGIN_VERSION: '0.51.0',
    GRADLE_SPOTLESS_PLUGIN_VERSION: '6.25.0',

    MAVEN_JACOCO_PLUGIN_VERSION: '0.8.12',
    MAVEN_SONAR_PLUGIN_VERSION: '5.0.0.4389',
    MAVEN_SPOTLESS_PLUGIN_VERSION: '2.43.0',
    MAVEN_JIB_PLUGIN_VERSION: '3.4.4',
    MAVEN_PROPERTIES_PLUGIN_VERSION: '1.2.1',

    KEY_FLYWAY_MIGRATION_COUNTER: 'flywayMigrationCounter',
    KEY_LIQUIBASE_MIGRATION_COUNTER: 'liquibaseMigrationCounter',

    LOCALSTACK_IMAGE_VERSION: LOCALSTACK_IMAGE_VERSION,
    LOCALSTACK_IMAGE: 'localstack/localstack:' + LOCALSTACK_IMAGE_VERSION,

    POSTGRESQL_IMAGE_VERSION: POSTGRESQL_IMAGE_VERSION,
    POSTGRESQL_IMAGE: 'postgres:' + POSTGRESQL_IMAGE_VERSION,

    MARIADB_IMAGE_VERSION: MARIADB_IMAGE_VERSION,
    MARIADB_IMAGE: 'mariadb:' + MARIADB_IMAGE_VERSION,

    MYSQL_IMAGE_VERSION: MYSQL_IMAGE_VERSION,
    MYSQL_IMAGE: 'mysql:' + MYSQL_IMAGE_VERSION,

    JAVA_IMAGE_VERSION: JAVA_IMAGE_VERSION,
    JAVA_IMAGE: 'eclipse-temurin:' + JAVA_IMAGE_VERSION,

    ES_IMAGE_VERSION: '8.16.1',
    GRAFANA_IMAGE_VERSION: '11.3.1',
    SONARQUBE_IMAGE_VERSION: '10.7.0-community',
    PROMETHEUS_IMAGE_VERSION: 'v3.0.1',
}
