services:
<%_ if (databaseType === 'postgresql') { _%>
  postgresql:
    image: <%= POSTGRESQL_IMAGE %>
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
<%_ } _%>
<%_ if (databaseType === 'mysql') { _%>
  mysql:
    image: <%= MYSQL_IMAGE %>
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  <%_ } _%>
<%_ if (databaseType === 'mariadb') { _%>
  mariadb:
    image: <%= MARIADB_IMAGE %>
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
<%_ } _%>
<%_ if (databaseType === 'mongodb') { _%>
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
<%_ } _%>
