services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: ["--config=/etc/otelcol-config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./docker/otel/otelcol-config.yml:/etc/otelcol-config.yml:ro
